# Generated by Django 2.2 on 2021-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame1', models.CharField(max_length=255)),
                ('goal1', models.CharField(max_length=255)),
                ('funame2', models.CharField(max_length=255)),
                ('goal2', models.CharField(max_length=255)),
                ('funame3', models.CharField(max_length=255)),
                ('goal3', models.CharField(max_length=255)),
                ('funame4', models.CharField(max_length=255)),
                ('goal4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfname', models.CharField(max_length=255)),
                ('slname', models.CharField(max_length=255)),
                ('caddress', models.CharField(max_length=255)),
                ('ccity', models.CharField(max_length=255)),
                ('cstate', models.CharField(max_length=255)),
                ('ctime', models.CharField(max_length=255)),
                ('raddress', models.CharField(max_length=255)),
                ('rcity', models.CharField(max_length=255)),
                ('rstate', models.CharField(max_length=255)),
                ('cdate', models.DateTimeField()),
                ('rtime', models.CharField(max_length=255)),
            ],
        ),
    ]
