# Generated by Django 2.2 on 2021-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0002_auto_20210830_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='registry_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_created', to='wedding_app.User'),
        ),
    ]
