# Generated by Django 2.2 on 2021-08-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0003_registry_registry_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registryfour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame4', models.CharField(max_length=255)),
                ('goal4', models.CharField(max_length=255)),
                ('registry_owner34', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_created4', to='wedding_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Registryone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame1', models.CharField(max_length=255)),
                ('goal1', models.CharField(max_length=255)),
                ('registry_owner1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_created1', to='wedding_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Registrythree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame3', models.CharField(max_length=255)),
                ('goal3', models.CharField(max_length=255)),
                ('registry_owner3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_created3', to='wedding_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Registrytwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame2', models.CharField(max_length=255)),
                ('goal2', models.CharField(max_length=255)),
                ('registry_owner2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_created2', to='wedding_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
