# Generated by Django 2.2 on 2021-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0005_auto_20210831_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='image',
            field=models.ImageField(null=True, upload_to='weddings'),
        ),
    ]
