# Generated by Django 2.2 on 2021-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0006_wedding_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='registry',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
