# Generated by Django 2.2 on 2021-09-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0007_auto_20210901_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='funame',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='goal',
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_created', to='wedding_app.User'),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funame', models.CharField(max_length=255)),
                ('goal', models.IntegerField()),
                ('fund_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_created', to='wedding_app.Registry')),
            ],
        ),
    ]
