# Generated by Django 2.2 on 2021-09-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0008_auto_20210901_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='funame',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rdate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_created', to='wedding_app.User'),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
