# Generated by Django 2.2 on 2021-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0010_auto_20210902_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
