# Generated by Django 2.2 on 2021-09-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0011_auto_20210902_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rtime',
            field=models.DateTimeField(),
        ),
    ]
