# Generated by Django 2.2 on 2021-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0012_auto_20210902_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='ctime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rtime',
            field=models.TimeField(),
        ),
    ]
