# Generated by Django 2.2 on 2021-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0013_auto_20210902_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='cvenue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='czip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='rvenue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='rzip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
