# Generated by Django 2.2 on 2021-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0014_auto_20210902_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='czip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rzip',
            field=models.IntegerField(null=True),
        ),
    ]
