# Generated by Django 2.2 on 2021-09-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0015_auto_20210902_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_created', to='wedding_app.User'),
        ),
    ]
