# Generated by Django 2.2 on 2021-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0016_auto_20210910_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credit',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='credit',
            name='card_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='card_zip',
            field=models.IntegerField(null=True),
        ),
    ]
