# Generated by Django 2.2 on 2021-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0018_wedding_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='remaining_balance',
            field=models.IntegerField(null=True),
        ),
    ]
